#%RAML 1.0 DataType

type:
    properties:
      Id:
        type: number
        description: "Student ID"
      Name:
        type: string
        description: "Student name"
      Contact:
        type: string
        description: "Contact Number"
      Age:
        type: number
        description: "Age"
      Email:
        type: string
        description: "Email"
      City:
        type: string
        description: "City"
      Speciality:
        type: string
        description: "Speciality"
      
      