#%RAML 1.0 DataType

type:
    properties:
      Id:
        type: number
        description: "Student ID"
      Name:
        type: string
        description: "Student name"
      Contact:
        type: string
        description: "Contact Number"
      Age:
        type: number
        description: "Age"
      City:
        type: string
        description: "City"
      Doctor:
        type: string
        description: "Name of the Doctor assigned"
      ReasonOfVisit:
        type: string
        description: "Reason of the Visit"
      
      